name: ExamplePlugin
main: com.publicuhc.exampleplugin.ExamplePlugin
version: 0.1
description: Example plugin for PluginFramework
author: ghowden/Eluinhost
website: publicuhc.com
database: false
commands:
  pm:
    description: Message players with a message
    usage: /<command> -m "message to send" player1 player2 player3/*
    aliases: [examplepm]
  translate:
    description: Returns the translated key
    usage: /<command> keyname
    aliases: [exampletranslate]
  config:
    description: Show a config value
    usage: /<command>
    aliases: [exampleconfig]